on: push
name: ðŸš€ Deploy website on push
jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ðŸšš Get latest code
        uses: actions/checkout@v4

      # OdstranÃ­ vÅ¡echny console.log z JS souborÅ¯ kromÄ› sloÅ¾ky tools///
      - name: Remove all console.log from JS files
        run: find . -type f -name "*.js" -not -path "*/tools/*" -exec sed -i '/console.log/d' {} +

      # NastavenÃ­ Node.js
      - name: ðŸ”§ Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      # PovolenÃ­ Corepack a sprÃ¡vnÃ© verze Yarn
      - name: Enable Corepack and Yarn 3
        run: |
          corepack enable
          corepack prepare yarn@3.6.1 --activate

      # Instalace zÃ¡vislostÃ­ a build projektu
      - name: ðŸ”¨ Build Project
        run: |
          yarn install
          yarn esbuild src/js/main.js --bundle --outfile=dist/js/main.js --format=iife

      # Kompilace SCSS souborÅ¯
      - name: ðŸŽ¨ Compile SCSS
        run: |
          npx sass src/scss/main.scss dist/css/main.css

      - name: SFTP Upload
        uses: Dylan700/sftp-upload-action@latest
        with:
          server: ftp.myshoptet.com
          username: git_444591
          password: ${{ secrets.SFTP_PASSWORD }}
          port: 22
          uploads: |
            ./dist/ => eshopy/mokso/dist/
          ignore: |
            .gitd
            node_modules
